FROM python:3.7-buster

COPY . /opt/faiss

WORKDIR /opt/faiss

RUN apt-get update -y && \
    apt-get install -y libopenblas-dev python-numpy python-dev swig python-pip wget && \
    mv example_makefiles/makefile.inc.Linux ./makefile.inc && \
    rm -rf /var/lib/apt/lists/*

ENV BLASLDFLAGS /usr/lib/libopenblas.so.0

RUN make -j 4 && \
    make py

ENV PYTHONPATH $PYTHONPATH:/opt/faiss
